In [1]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\pc\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\pc\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\pc\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\pc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

# PHASE I: DATA PREPROCESSING & EDA 8 DATASET

## DATASET 1: ORDERS DATASET

In [5]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\orders_dataset.csv"
df_orders_raw = pd.read_csv(file_path)
df_orders_raw.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02/10/2017 10:56,02/10/2017 11:07,04/10/2017 19:55,10/10/2017 21:25,18/10/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24/07/2018 20:41,26/07/2018 3:24,26/07/2018 14:31,07/08/2018 15:27,13/08/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08/08/2018 8:38,08/08/2018 8:55,08/08/2018 13:50,17/08/2018 18:06,04/09/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18/11/2017 19:28,18/11/2017 19:45,22/11/2017 13:39,02/12/2017 0:28,15/12/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13/02/2018 21:18,13/02/2018 22:20,14/02/2018 19:46,16/02/2018 18:17,26/02/2018 0:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,09/07/2017 21:57,09/07/2017 22:10,11/07/2017 14:58,26/07/2017 10:57,01/08/2017 0:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,11/04/2017 12:22,13/04/2017 13:25,NaN,NaN,09/05/2017 0:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,16/05/2017 13:10,16/05/2017 13:22,22/05/2017 10:07,26/05/2017 12:55,07/06/2017 0:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,23/01/2017 18:29,25/01/2017 2:50,26/01/2017 14:16,02/02/2017 14:08,06/03/2017 0:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,29/07/2017 11:55,29/07/2017 12:05,10/08/2017 19:45,16/08/2017 17:14,23/08/2017 0:00

### 1.1. Dealing with Conversion

In [7]:
df_orders_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [8]:
time_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
for i in time_columns:
    df_orders_raw[i] = pd.to_datetime(
        df_orders_raw[i], 
        dayfirst=True, 
        format='mixed')

df_orders_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

### 1.2. Dealing with Missing Values

In [10]:
df_orders_raw.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
df_orders_no_missing = df_orders_raw.dropna(axis=0)

In [12]:
df_orders_no_missing.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [13]:
df_orders_no_missing = df_orders_no_missing.reset_index(drop=True)
df_orders_no_missing.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26

### 1.3. Dealing with Duplicate & Non-Unique Values

In [15]:
df_orders_no_missing.duplicated().sum()

0

In [16]:
df_orders_no_missing['customer_id'].is_unique

True

In [17]:
df_orders_no_missing['order_id'].is_unique

True

### 1.4. Feature Construction

In [19]:
df_orders_featured = df_orders_no_missing.copy()

In [20]:
# Speed & Efficiency
df_orders_featured['order_approval_time'] = df_orders_featured['order_approved_at'] - df_orders_featured['order_purchase_timestamp']
df_orders_featured['seller_handling_time'] = df_orders_featured['order_delivered_carrier_date'] - df_orders_featured['order_approved_at']
df_orders_featured['carrier_transit_time'] = df_orders_featured['order_delivered_customer_date'] - df_orders_featured['order_delivered_carrier_date']
df_orders_featured['total_delivery_lead_time'] = df_orders_featured['order_delivered_customer_date'] - df_orders_featured['order_purchase_timestamp']

In [21]:
df_orders_featured['check'] = (df_orders_featured['order_approval_time'] + df_orders_featured['seller_handling_time'] + df_orders_featured['carrier_transit_time']) - df_orders_featured['total_delivery_lead_time']
df_orders_featured['check'].sum()

Timedelta('0 days 00:00:00')

In [22]:
# Reliability & Promise Keeping
df_orders_featured['promise_gap'] = df_orders_featured['order_delivered_customer_date'] - df_orders_featured['order_estimated_delivery_date']

In [23]:
time_columns = ['order_approval_time',
                'seller_handling_time',
                'carrier_transit_time',
                'total_delivery_lead_time',
                'promise_gap'
]
for i in time_columns:
    df_orders_featured[i] = df_orders_featured[i] / pd.Timedelta(days=1)

In [24]:
# Measure by Minutes 
df_orders_featured['order_approval_time'] = df_orders_featured['order_approval_time']*60*24

In [25]:
df_orders_featured = df_orders_featured.drop(columns = ['check'])
df_orders_featured.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,11.0,2.366667,6.062500,8.436806,-7.107639
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,1843.0,0.463194,12.038889,13.781944,-5.356250
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,17.0,0.204861,9.177778,9.394444,-17.245833
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,17.0,3.745833,9.450694,13.208333,-12.980556
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,62.0,0.893056,1.938194,2.874306,-9.238194

In [26]:
total_delivered_orders = df_orders_featured[df_orders_featured['order_status'] == 'delivered'].shape[0]
total_late_orders = df_orders_featured[(df_orders_featured['promise_gap'] > 0) & (df_orders_featured['order_status'] == 'delivered')].shape[0]

late_delivery_rate = round((total_late_orders / total_delivered_orders) * 100, 2)
late_delivery_rate

8.11

In [27]:
df_orders_featured['order_status'].value_counts(normalize=True)*100

order_status
delivered    99.99378
canceled      0.00622
Name: proportion, dtype: float64

In [28]:
late_orders_df = df_orders_featured[(df_orders_featured['promise_gap'] > 0) & (df_orders_featured['order_status'] == 'delivered')]
late_orders_df['promise_gap'].quantile([0.9, 0.95, 0.99])

0.90    21.540417
0.95    29.639583
0.99    62.813278
Name: promise_gap, dtype: float64

### 1.5. Descriptive Statistics Overview

In [30]:
late_orders_df.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap
count,7825,7825,7825,7825,7825,7825.000000,7825.000000,7825.000000,7825.000000,7825.000000
mean,2018-01-25 14:00:52.301597184,2018-01-26 02:19:50.039616512,2018-01-31 10:01:33.293290752,2018-02-26 02:24:09.086262016,2018-02-16 13:09:39.220447232,738.962300,5.320640,25.682359,31.516166,9.551735
min,2016-09-15 12:16:00,2016-09-15 12:16:00,2016-11-07 17:11:00,2016-11-09 07:47:00,2016-10-04 00:00:00,0.000000,-9.045833,0.000000,2.129861,0.002083
25%,2017-11-24 23:09:00,2017-11-25 10:16:00,2017-11-29 23:47:00,2017-12-26 22:23:00,2017-12-19 00:00:00,14.000000,1.263889,15.262500,22.353472,1.866667
50%,2018-02-21 20:29:00,2018-02-22 02:30:00,2018-02-26 21:49:00,2018-03-23 23:18:00,2018-03-16 00:00:00,25.000000,3.006250,23.918750,29.153472,5.804861
75%,2018-03-31 12:04:00,2018-03-31 19:50:00,2018-04-04 21:03:00,2018-05-07 13:35:00,2018-04-24 00:00:00,1156.000000,6.146528,33.085417,37.934722,11.820833
max,2018-08-28 22:51:00,2018-08-28 23:05:00,2018-09-11 19:48:00,2018-10-17 13:22:00,2018-08-31 00:00:00,44487.000000,125.762500,205.190972,209.628472,188.975000
std,NaN,NaN,NaN,NaN,NaN,1563.286507,7.059580,17.751236,17.259090,13.953398

## DATASET 2: CUSTOMERS DATASET

In [32]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\customers_dataset.csv"
df_customers = pd.read_csv(file_path)
df_customers.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### 2.1. Dealing with Conversion

In [34]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [35]:
df_customers['customer_zip_code_prefix'] = df_customers['customer_zip_code_prefix'].astype(str).str.zfill(5)

### 2.2. Dealing with Missing Values

In [37]:
df_customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

### 2.3. Dealing with Duplicate & Non-Unique Values

In [39]:
df_customers.duplicated().sum()

0

In [40]:
df_customers['customer_unique_id'].is_unique

False

In [41]:
df_customers['customer_id'].is_unique

True

In [42]:
df_customers['customer_zip_code_prefix'].is_unique

False

### 2.4. Descriptive Statistics Overview

In [44]:
df_customers.describe()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441,99441,99441
unique,99441,96096,14994,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,22790,sao paulo,SP
freq,1,17,142,15540,41746

## DATASET 3: SELLERS DATASET

In [46]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\sellers_dataset.csv"
df_sellers = pd.read_csv(file_path, encoding='latin1')
df_sellers.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

### 3.1. Dealing with Conversion

In [48]:
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

### 3.2. Dealing with Missing Values

In [50]:
df_sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

### 3.3.  Dealing with Duplicate & Non-Unique Values

In [52]:
df_sellers.duplicated().sum()

0

In [53]:
df_sellers['seller_id'].is_unique

True

In [54]:
df_sellers['seller_zip_code_prefix'].is_unique

False

In [55]:
df_sellers['seller_zip_code_prefix'] = df_sellers['seller_zip_code_prefix'].astype(str).str.zfill(5)

In [56]:
df_sellers.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

### 3.4. Descriptive Statistics Overview

In [58]:
df_sellers.describe()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095,3095,3095
unique,3095,2246,611,23
top,3442f8959a84dea7ee197c632cb2df15,14940,sao paulo,SP
freq,1,49,694,1849

## DATASET 4: ORDER REVIEW DATASET

In [60]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\order_reviews_dataset.csv"

df_reviews = pd.read_csv(file_path, lineterminator='\n')
df_reviews.columns = df_reviews.columns.str.replace('\r', '')
df_reviews['review_answer_timestamp'] = df_reviews['review_answer_timestamp'].astype(str).str.replace('\r', '')

df_reviews.head(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18/01/2018 0:00,18/01/2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10/03/2018 0:00,11/03/2018 3:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17/02/2018 0:00,18/02/2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21/04/2017 0:00,21/04/2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01/03/2018 0:00,02/03/2018 10:26

### 4.1. Dealing with Conversion

In [62]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104719 entries, 0 to 104718
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                104163 non-null  object
 1   order_id                 101926 non-null  object
 2   review_score             101782 non-null  object
 3   review_comment_title     12005 non-null   object
 4   review_comment_message   41045 non-null   object
 5   review_creation_date     95396 non-null   object
 6   review_answer_timestamp  104719 non-null  object
dtypes: object(7)
memory usage: 5.6+ MB

In [63]:
df_reviews_converted = df_reviews.copy()
df_reviews_converted['review_score'] = pd.to_numeric(df_reviews_converted['review_score'], errors='coerce')
df_reviews_converted['review_answer_timestamp'] = pd.to_datetime(df_reviews_converted['review_answer_timestamp'], dayfirst = True, format='mixed')
df_reviews_converted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104719 entries, 0 to 104718
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                104163 non-null  object
 1   order_id                 101926 non-null  object
 2   review_score             99227 non-null   float64
 3   review_comment_title     12005 non-null   object
 4   review_comment_message   41045 non-null   object
 5   review_creation_date     95396 non-null   object
 6   review_answer_timestamp  95377 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 5.6+ MB

### 4.2. Dealing with Missing Values

In [65]:
df_reviews_converted.isna().sum()

review_id                    556
order_id                    2793
review_score                5492
review_comment_title       92714
review_comment_message     63674
review_creation_date        9323
review_answer_timestamp     9342
dtype: int64

In [66]:
df_reviews_no_missing = df_reviews_converted.dropna(subset =['order_id', 'review_score'])
df_reviews_no_missing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99227 entries, 0 to 104718
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99227 non-null  object
 1   order_id                 99227 non-null  object
 2   review_score             99227 non-null  float64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40939 non-null  object
 5   review_creation_date     95372 non-null  object
 6   review_answer_timestamp  95372 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 6.1+ MB

### 4.3. Dealing with Duplicate & Non-Unique Values

In [68]:
df_reviews_no_missing.duplicated().sum()

0

In [69]:
df_reviews_no_missing['order_id'].is_unique

False

### 4.4. Field Validity & Structural Checks

In [71]:
# Check malformed review records
invalid_review_rows = df_reviews_no_missing[
    (~df_reviews_no_missing['review_id'].astype(str).str.match(r'^[a-f0-9]{32}$', na=False)) |
    (~df_reviews_no_missing['order_id'].astype(str).str.match(r'^[a-f0-9]{32}$', na=False)) |
    (~df_reviews_no_missing['review_score'].between(1, 5))
]
invalid_review_rows

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
27951,Conforme outros sites,poderia ser livre acima de 100,0.0,NaN,NaN,NaN,NaT
40825,no valor de 199,00 mas me mandaram o produto da edição especia...,90.0,NaN,NaN,NaN,NaT
65219,O valor do frete calculado foi R$ 18,90 e veio R$ 93,0.0,NaN,NaN,NaN,NaT

In [72]:
# Keep only valid review records
valid_review_rows = (
    df_reviews_no_missing['review_id'].astype(str).str.match(r'^[a-f0-9]{32}$', na=False) &
    df_reviews_no_missing['order_id'].astype(str).str.match(r'^[a-f0-9]{32}$', na=False) &
    df_reviews_no_missing['review_score'].between(1, 5)
)
df_reviews_valid = df_reviews_no_missing[valid_review_rows]
df_reviews_valid = df_reviews_valid.reset_index(drop=True)

df_reviews_valid.head(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4.0,NaN,NaN,18/01/2018 0:00,2018-01-18 21:46:00
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5.0,NaN,NaN,10/03/2018 0:00,2018-03-11 03:05:00
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5.0,NaN,NaN,17/02/2018 0:00,2018-02-18 14:36:00
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5.0,NaN,Recebi bem antes do prazo estipulado.,21/04/2017 0:00,2017-04-21 22:02:00
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5.0,NaN,Parabéns lojas lannister adorei comprar pela I...,01/03/2018 0:00,2018-03-02 10:26:00

### Order-level Review Consolidation

Some orders contain multiple review records because items within the same order may be delivered at different times, or customers may update their feedback after the initial review.

In this project, the `orders` dataset is the primary source for delivery time and delivery performance analysis. However, this dataset stores delivery information at the order level, not at the individual item level. In other words, each `order_id` represents the overall order delivery outcome rather than separate delivery records for each item within that order.

Since the review dataset does not provide item-level review mapping, multiple reviews from the same order cannot be accurately linked to specific individual items or separate delivery events.

To keep the review data consistent with the order-level structure of the `orders` dataset, only the most recent review for each `order_id` is retained based on `review_answer_timestamp`.

The latest review score is used as the final measure of the customer's overall satisfaction with the complete order and its delivery performance.

In [74]:
# Sort reviews by order_id and latest response timestamp
df_reviews_sorted = df_reviews_valid.sort_values(
    by=['order_id', 'review_answer_timestamp'],
    ascending=[True, False]
)

# Keep the latest review for each order
df_reviews_order_level = df_reviews_sorted.drop_duplicates(
    subset='order_id',
    keep='first'
)

df_reviews_order_level = df_reviews_order_level.reset_index(drop=True)
df_reviews_order_level.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,97ca439bc427b48bc1cd7177abe71365,00010242fe8c5a6d1ba2dd792cb16214,5.0,NaN,"Perfeito, produto entregue antes do combinado.",21/09/2017 0:00,2017-09-22 10:57:00
1,7b07bacd811c4117b742569b04ce3580,00018f77f2f0320c557190d7a144bdd3,4.0,NaN,NaN,13/05/2017 0:00,2017-05-15 11:34:00
2,0c5b33dea94867d1ac402749e5438e8b,000229ec398224ef6ca0657da4fc703e,5.0,NaN,Chegou antes do prazo previsto e o produto sur...,23/01/2018 0:00,2018-01-23 16:06:00
3,f4028d019cb58564807486a6aaf33817,00024acbcdf0a6daa1e931b038114c75,4.0,NaN,NaN,15/08/2018 0:00,2018-08-15 16:39:00
4,940144190dcba6351888cafa43f3a3a5,00042b26cf59d7ce69dfabb4e55b4fd9,5.0,NaN,Gostei pois veio no prazo determinado .,02/03/2017 0:00,2017-03-03 10:54:00

In [75]:
df_reviews_order_level['order_id'].is_unique

True

### 4.5. Descriptive Statistics Overview

In [77]:
df_reviews_order_level.describe()

       review_score        review_answer_timestamp
count  98673.000000                          94866
mean       4.086478  2018-01-16 11:01:37.600404992
min        1.000000            2016-10-07 18:32:00
25%        4.000000            2017-09-27 15:52:45
50%        5.000000            2018-02-05 11:25:00
75%        5.000000            2018-05-20 14:52:45
max        5.000000            2018-10-29 12:27:00
std        1.347458                            NaN

## DATASET 5: PRODUCTS DATASET

In [79]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\products_dataset.csv"
df_products = pd.read_csv(file_path)
df_products.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

### 5.1. Dealing with Conversion

In [81]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

### 5.2. Dealing with Missing Values

In [83]:
df_products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [84]:
df_products_valid = df_products.dropna(subset = ['product_category_name','product_weight_g'])
df_products_valid.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

### 5.3. Dealing with Duplicate & Non-Unique Values

In [86]:
df_products_valid.duplicated().sum()

0

In [87]:
df_products_valid['product_id'].is_unique

True

In [88]:
df_products_valid['product_category_name'].is_unique

False

### 5.4. Descriptive Statistics Overview

In [90]:
df_products_valid.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32340.000000,32340.000000,32340.000000,32340.000000,32340.000000,32340.000000,32340.000000
mean,48.476592,771.492393,2.188961,2276.956586,30.854545,16.958813,23.208596
std,10.245699,635.124831,1.736787,4279.291845,16.955965,13.636115,12.078762
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

## 6. PRODUCT CATEGORY NAME TRANS

In [92]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\product_category_name_trans.csv"
df_product_name_trans = pd.read_csv(file_path)

df_product_name_trans.head(5)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

### 6.1. Dealing with Conversion

In [94]:
df_product_name_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

### 6.2. Dealing with Missing Values

In [96]:
df_product_name_trans.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

### 6.3. Dealing with Duplicate & Non-Unique Values

In [98]:
df_product_name_trans.duplicated().sum()

0

In [99]:
df_product_name_trans['product_category_name'].is_unique

True

### 6.4. Descriptive Statistics Overview

In [101]:
df_product_name_trans.describe()

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

## DATASET 7: ORDER ITEMS DATASET

In [103]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\order_items_dataset.csv"
df_order_items = pd.read_csv(file_path)

df_order_items.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19/09/2017 9:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03/05/2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18/01/2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15/08/2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13/02/2017 13:57,199.90,18.14

### 7.1. Dealing with Conversion

In [105]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

### 7.2. Dealing with Missing Values

In [107]:
df_order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

### 7.3. Dealing with Duplicate & Non-Unique Values

In [109]:
df_order_items.duplicated().sum()

0

In [110]:
df_order_items['product_id'].is_unique

False

In [111]:
df_order_items['seller_id'].is_unique

False

In [112]:
df_order_items['order_id'].is_unique

False

### 7.4. Master Whole-order Table Construction

### Methodology: Master Whole-order Table Construction

This project is structured at the **order level** because the Olist dataset records delivery outcomes by `order_id`, not by individual item.

Although a single order may contain multiple items, products, or sellers, the delivery timestamps describe the overall delivery journey of the complete order. Therefore, `order_id` is used as the main unit of observation.

To build a consistent order-level dataset, the `orders` dataset is used as the central table because it contains the complete set of delivery timestamps and the unique `order_id`.

Before joining datasets, item-level information is first aggregated to one row per order. The `order_items` dataset is enriched with product information from the `products` dataset, then grouped by `order_id` to create order-level features such as:

- number of items;
- number of unique products;
- number of sellers;
- total product value;
- total freight cost;
- total product weight;
- total product volume.

These variables are not intended to identify which specific item caused a delivery delay. Instead, they describe the overall size, value, and operational complexity of each order.

The deduplicated `reviews` dataset is then joined to capture the final customer satisfaction outcome for each order, while customer-level information from the `customers` dataset is added to provide basic customer and geographic context.

After the master order-level table is created, each order is classified into one of two structural groups:

- **Homogeneous orders:** orders containing only one product type and one seller.
- **Complex orders:** orders containing multiple product types, multiple sellers, or both.

As a result, the final master table provides a unified and methodologically consistent foundation for analyzing delivery performance and customer satisfaction at the order level.

In [115]:
# Create product-level features from the original products table
df_products_features = df_products.copy()

df_products_features['product_volume_cm3'] = (
    df_products_features['product_length_cm'] *
    df_products_features['product_height_cm'] *
    df_products_features['product_width_cm']
)

df_products_features.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,2240.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,10800.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,2430.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,2704.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,4420.0

In [116]:
# Select product columns needed for order-level aggregation
product_cols = [
    'product_id',
    'product_category_name',
    'product_weight_g',
    'product_volume_cm3'
]

df_order_items_enriched = df_order_items.merge(
    df_products_features[product_cols],
    on='product_id',
    how='left'
)

df_order_items_enriched.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_weight_g,product_volume_cm3
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19/09/2017 9:45,58.90,13.29,cool_stuff,650.0,3528.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03/05/2017 11:05,239.90,19.93,pet_shop,30000.0,60000.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18/01/2018 14:48,199.00,17.87,moveis_decoracao,3050.0,14157.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15/08/2018 10:10,12.99,12.79,perfumaria,200.0,2400.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13/02/2017 13:57,199.90,18.14,ferramentas_jardim,3750.0,42000.0

In [117]:
# Check missing product information after merging
df_order_items_enriched[
    ['product_category_name', 'product_weight_g', 'product_volume_cm3']
].isna().sum()

product_category_name    1603
product_weight_g           18
product_volume_cm3         18
dtype: int64

In [118]:
# Fill missing weight and volume using median values
df_order_items_enriched['product_weight_g'] = (
    df_order_items_enriched['product_weight_g']
    .fillna(df_order_items_enriched['product_weight_g'].median())
)

df_order_items_enriched['product_volume_cm3'] = (
    df_order_items_enriched['product_volume_cm3']
    .fillna(df_order_items_enriched['product_volume_cm3'].median())
)

In [119]:
# Build order-level features from item-level data
df_order_features = df_order_items_enriched.groupby('order_id').agg(
    item_count=('order_item_id', 'count'),
    product_count=('product_id', 'nunique'),
    category_count=('product_category_name', 'nunique'),
    seller_count=('seller_id', 'nunique'),
    total_price=('price', 'sum'),
    total_freight=('freight_value', 'sum'),
    total_weight_g=('product_weight_g', 'sum'),
    total_volume_cm3=('product_volume_cm3', 'sum')
).reset_index()

df_order_features.head(5)

,order_id,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,1,58.90,13.29,650.0,3528.0
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,1,239.90,19.93,30000.0,60000.0
2,000229ec398224ef6ca0657da4fc703e,1,1,1,1,199.00,17.87,3050.0,14157.0
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,1,12.99,12.79,200.0,2400.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,1,199.90,18.14,3750.0,42000.0

In [120]:
# Create order structure flags
df_order_features['multi_seller_flag'] = (
    df_order_features['seller_count'] > 1
).astype(int)

df_order_features['multi_product_flag'] = (
    df_order_features['product_count'] > 1
).astype(int)

df_order_features['freight_to_price_ratio'] = np.where(
    df_order_features['total_price'] > 0,
    df_order_features['total_freight'] / df_order_features['total_price'],
    0
)

In [121]:
# Classify order structure type
df_order_features['order_structure_type'] = np.where(
    (df_order_features['product_count'] == 1) &
    (df_order_features['seller_count'] == 1),
    'Homogeneous',
    'Complex'
)

df_order_features.head(5)

,order_id,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,1,58.90,13.29,650.0,3528.0,0,0,0.225637,Homogeneous
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,1,239.90,19.93,30000.0,60000.0,0,0,0.083076,Homogeneous
2,000229ec398224ef6ca0657da4fc703e,1,1,1,1,199.00,17.87,3050.0,14157.0,0,0,0.089799,Homogeneous
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,1,12.99,12.79,200.0,2400.0,0,0,0.984604,Homogeneous
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,1,199.90,18.14,3750.0,42000.0,0,0,0.090745,Homogeneous

In [122]:
# Check whether each order appears only once
print("Is order_id unique:", df_order_features['order_id'].is_unique)
print("Order-level feature rows:", len(df_order_features))

Is order_id unique: True
Order-level feature rows: 98666

In [123]:
# Select review columns needed for the master table
review_cols = [
    'order_id',
    'review_id',
    'review_score',
    'review_creation_date',
    'review_answer_timestamp'
]
# Select customer columns needed for the master table
customer_cols = [
    'customer_id',
    'customer_unique_id',
    'customer_zip_code_prefix',
    'customer_city',
    'customer_state'
]

In [124]:
# Build the master whole-order table
df_master_orders_core = df_orders_featured.merge(
    df_order_features,
    on='order_id',
    how='left'
)
df_master_orders_core = df_master_orders_core.merge(
    df_reviews_order_level[review_cols],
    on='order_id',
    how='left'
)
df_master_orders_core = df_master_orders_core.merge(
    df_customers[customer_cols],
    on='customer_id',
    how='left'
)

df_master_orders_core.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type,review_id,review_score,review_creation_date,review_answer_timestamp,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,11.0,2.366667,6.062500,8.436806,-7.107639,1,1,1,1,29.99,8.72,500.0,1976.0,0,0,0.290764,Homogeneous,a54f0611adc9ed256b57ede6b6eb5114,4.0,11/10/2017 0:00,2017-10-12 03:43:00,7c396fd4830fd04220f754e42b4e5bff,03149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,1843.0,0.463194,12.038889,13.781944,-5.356250,1,1,1,1,118.70,22.76,400.0,4693.0,0,0,0.191744,Homogeneous,8d5266042046a06655c8db133d120ba5,4.0,08/08/2018 0:00,2018-08-08 18:37:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,17.0,0.204861,9.177778,9.394444,-17.245833,1,1,1,1,159.90,19.22,420.0,9576.0,0,0,0.120200,Homogeneous,e73b67b67587f7644d5bd1a52deb1b01,5.0,18/08/2018 0:00,2018-08-22 19:07:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,17.0,3.745833,9.450694,13.208333,-12.980556,1,1,1,1,45.00,27.20,450.0,6000.0,0,0,0.604444,Homogeneous,359d03e676b3c069f62cadba8dd3f6e8,5.0,03/12/2017 0:00,2017-12-05 19:21:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,62.0,0.893056,1.938194,2.874306,-9.238194,1,1,1,1,19.90,8.72,250.0,11475.0,0,0,0.438191,Homogeneous,e50934924e227544ba8246aeb3770dd4,5.0,17/02/2018 0:00,2018-02-18 13:02:00,72632f0f9dd73dfee390c9b22eb56dd6,09195,santo andre,SP

In [125]:
# Check final master table structure
print("Master table rows:", len(df_master_orders_core))
print("Master table columns:", len(df_master_orders_core.columns))
print("Is order_id unique:", df_master_orders_core['order_id'].is_unique)

Master table rows: 96461
Master table columns: 33
Is order_id unique: True

In [126]:
df_master_orders_core.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
order_approval_time                 0
seller_handling_time                0
carrier_transit_time                0
total_delivery_lead_time            0
promise_gap                         0
item_count                          0
product_count                       0
category_count                      0
seller_count                        0
total_price                         0
total_freight                       0
total_weight_g                      0
total_volume_cm3                    0
multi_seller_flag                   0
multi_product_flag                  0
freight_to_price_ratio              0
order_structure_type                0
review_id                         646
review_score                      646
review_creation_date             4257
review_answer_timestamp          4257
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
dtype: int64

In [127]:
# Remove orders without review score
df_master_orders_reviewed = df_master_orders_core.dropna(subset=['review_score'])
df_master_orders_reviewed = df_master_orders_reviewed.reset_index(drop=True)
df_master_orders_reviewed.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
order_approval_time                 0
seller_handling_time                0
carrier_transit_time                0
total_delivery_lead_time            0
promise_gap                         0
item_count                          0
product_count                       0
category_count                      0
seller_count                        0
total_price                         0
total_freight                       0
total_weight_g                      0
total_volume_cm3                    0
multi_seller_flag                   0
multi_product_flag                  0
freight_to_price_ratio              0
order_structure_type                0
review_id                           0
review_score                        0
review_creation_date             3611
review_answer_timestamp          3611
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
dtype: int64

In [128]:
# Drop review metadata columns that are not needed for analysis
review_cols_to_drop = [
    'review_id',
    'review_creation_date',
    'review_answer_timestamp'
]
df_master_orders_reviewed = df_master_orders_reviewed.drop(
    columns=review_cols_to_drop
)
df_master_orders_reviewed.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type,review_score,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,11.0,2.366667,6.062500,8.436806,-7.107639,1,1,1,1,29.99,8.72,500.0,1976.0,0,0,0.290764,Homogeneous,4.0,7c396fd4830fd04220f754e42b4e5bff,03149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,1843.0,0.463194,12.038889,13.781944,-5.356250,1,1,1,1,118.70,22.76,400.0,4693.0,0,0,0.191744,Homogeneous,4.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,17.0,0.204861,9.177778,9.394444,-17.245833,1,1,1,1,159.90,19.22,420.0,9576.0,0,0,0.120200,Homogeneous,5.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,17.0,3.745833,9.450694,13.208333,-12.980556,1,1,1,1,45.00,27.20,450.0,6000.0,0,0,0.604444,Homogeneous,5.0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,62.0,0.893056,1.938194,2.874306,-9.238194,1,1,1,1,19.90,8.72,250.0,11475.0,0,0,0.438191,Homogeneous,5.0,72632f0f9dd73dfee390c9b22eb56dd6,09195,santo andre,SP

In [129]:
df_master_orders_reviewed.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
order_approval_time              0
seller_handling_time             0
carrier_transit_time             0
total_delivery_lead_time         0
promise_gap                      0
item_count                       0
product_count                    0
category_count                   0
seller_count                     0
total_price                      0
total_freight                    0
total_weight_g                   0
total_volume_cm3                 0
multi_seller_flag                0
multi_product_flag               0
freight_to_price_ratio           0
order_structure_type             0
review_score                     0
customer_unique_id               0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
dtype: int64

### 7.5. Descriptive Statistics Overview

In [131]:
df_master_orders_reviewed.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,multi_seller_flag,multi_product_flag,freight_to_price_ratio,review_score
count,95815,95815,95815,95815,95815,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,95815.000000,9.581500e+04,95815.000000,95815.000000,95815.000000,95815.000000
mean,2018-01-02 03:29:59.969942016,2018-01-02 13:46:38.445337088,2018-01-05 08:48:22.713771520,2018-01-14 15:54:00.990032896,2018-01-25 21:03:59.749517312,616.641257,2.792873,9.295582,12.516678,-11.215263,1.141293,1.038324,0.993863,1.013850,136.800513,22.762962,2382.354350,1.729264e+04,0.013161,0.032980,0.308458,4.155727
min,2016-09-15 12:16:00,2016-09-15 12:16:00,2016-10-08 10:34:00,2016-10-11 13:46:00,2016-10-04 00:00:00,0.000000,-171.218750,-16.096528,0.533333,-146.016667,1.000000,1.000000,0.000000,1.000000,0.850000,0.000000,0.000000,1.680000e+02,0.000000,0.000000,0.000000,1.000000
25%,2017-09-14 10:34:30,2017-09-14 16:37:30,2017-09-18 18:02:00,2017-09-26 13:53:00,2017-10-05 00:00:00,13.000000,0.874306,4.094792,6.756944,-16.247917,1.000000,1.000000,1.000000,1.000000,45.900000,13.840000,300.000000,2.964000e+03,0.000000,0.000000,0.132028,4.000000
50%,2018-01-21 00:05:00,2018-01-22 13:54:00,2018-01-24 18:02:00,2018-02-02 20:58:00,2018-02-16 00:00:00,21.000000,1.815278,7.095139,10.204861,-11.972917,1.000000,1.000000,1.000000,1.000000,86.250000,17.160000,750.000000,7.200000e+03,0.000000,0.000000,0.224374,5.000000
75%,2018-05-06 00:15:00,2018-05-06 16:22:30,2018-05-08 15:13:30,2018-05-16 12:00:30,2018-05-28 00:00:00,871.000000,3.570486,12.013889,15.664583,-6.407292,1.000000,1.000000,1.000000,1.000000,149.900000,23.990000,2050.000000,1.980000e+04,0.000000,0.000000,0.380585,5.000000
max,2018-08-29 15:00:00,2018-08-29 15:10:00,2018-09-11 19:48:00,2018-10-17 13:22:00,2018-10-25 00:00:00,44487.000000,125.762500,205.190972,208.352083,188.975000,21.000000,8.000000,3.000000,5.000000,13440.000000,1794.960000,184400.000000,1.476000e+06,1.000000,1.000000,21.447059,5.000000
std,NaN,NaN,NaN,NaN,NaN,1232.249315,3.519386,8.679762,9.460701,10.115465,0.534129,0.227231,0.147494,0.123383,207.795410,21.523560,4765.513905,3.004399e+04,0.113964,0.178586,0.311801,1.284890

## DATASET 8: GEOGRAPHY DATASET

In [133]:
file_path = r"C:\Users\PC\Downloads\SAT FILE\DATA ANALYST TOOLS\OLIST Project\Olist- Brazil E-Commerce\Raw Data\geolocation_dataset.csv"
df_geo = pd.read_csv(file_path, encoding='latin1')

In [134]:
df_geo['geolocation_zip_code_prefix'] = df_geo['geolocation_zip_code_prefix'].astype(str).str.zfill(5)

In [135]:
df_geo.head(5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545621,-46.639292,sao paulo,SP
1,01046,-23.546081,-46.644820,sao paulo,SP
2,01046,-23.546129,-46.642951,sao paulo,SP
3,01041,-23.544392,-46.639499,sao paulo,SP
4,01035,-23.541578,-46.641607,sao paulo,SP

In [136]:
df_geo['geolocation_zip_code_prefix'].is_unique

False

### Methodology: Geolocation Data Preparation and Integration

A key methodological challenge in this project is handling the `geolocation` dataset. In the raw Olist data, a single `geolocation_zip_code_prefix` can appear multiple times with slightly different latitude and longitude values. If this table is joined directly to the master dataset, it may create duplicate rows and many-to-many merge issues.

To avoid this problem, the geolocation data is first collapsed to one row per zip code prefix. For each `geolocation_zip_code_prefix`, the latitude and longitude are averaged, while the most frequent city and state values are retained. This creates a stable geographic reference table that can be safely joined to the order-level master dataset.

These geographic fields are treated as approximate location proxies, not exact address-level coordinates. This reflects a practical analytics approach: the goal is not to force artificial precision, but to build reliable geographic features that support meaningful operational analysis.

Another important decision involves seller geography. Since delivery outcomes in the Olist dataset are recorded once per completed order, a single seller location can only validly represent orders fulfilled by one seller. For multi-seller orders, assigning one arbitrary seller location would be misleading.

Therefore, seller geolocation is directly assigned only to single-seller orders. For complex or multi-seller orders, seller-related complexity is captured through variables such as `seller_count` and `multi_seller_flag`. This keeps the analysis consistent with the order-level structure while still preserving useful information about operational complexity.

In [138]:
# Function to get the most frequent value
def first_mode(x):
    mode_value = x.mode()
    return mode_value.iloc[0] if not mode_value.empty else x.iloc[0]


# Collapse geolocation data to one row per zip code prefix
df_geo_clean = df_geo.groupby('geolocation_zip_code_prefix').agg(
    geolocation_lat=('geolocation_lat', 'mean'),
    geolocation_lng=('geolocation_lng', 'mean'),
    geolocation_city=('geolocation_city', first_mode),
    geolocation_state=('geolocation_state', first_mode)
).reset_index()

df_geo_clean.head(5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01001,-23.550190,-46.634024,sao paulo,SP
1,01002,-23.548146,-46.634979,sao paulo,SP
2,01003,-23.548994,-46.635731,sao paulo,SP
3,01004,-23.549799,-46.634757,sao paulo,SP
4,01005,-23.549456,-46.636733,sao paulo,SP

In [139]:
# Check geolocation reference table
print("Is geolocation_zip_code_prefix unique:", df_geo_clean['geolocation_zip_code_prefix'].is_unique)
print("Rows before cleaning:", len(df_geo))
print("Rows after cleaning:", len(df_geo_clean))

Is geolocation_zip_code_prefix unique: True
Rows before cleaning: 1000163
Rows after cleaning: 19015

# PHASE II: FINAL MASTER WHOLE-ORDER DATASET

## 1. Master Table Construction

In [142]:
# Rename geolocation columns for customer location
df_customer_geo = df_geo_clean.rename(columns={
    'geolocation_zip_code_prefix': 'customer_zip_code_prefix',
    'geolocation_lat': 'customer_lat',
    'geolocation_lng': 'customer_lng',
    'geolocation_city': 'customer_geo_city',
    'geolocation_state': 'customer_geo_state'
})
# Add customer geolocation
df_customers_enriched = df_customers.merge(
    df_customer_geo,
    on='customer_zip_code_prefix',
    how='left',
    validate='m:1'
)
df_customers_enriched.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_lat,customer_lng,customer_geo_city,customer_geo_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,-20.498489,-47.396929,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP,-23.727992,-46.542848,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP,-23.531642,-46.656289,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP,-23.499702,-46.185233,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,-22.975100,-47.142925,campinas,SP

In [143]:
# Rename geolocation columns for seller location
df_seller_geo = df_geo_clean.rename(columns={
    'geolocation_zip_code_prefix': 'seller_zip_code_prefix',
    'geolocation_lat': 'seller_lat',
    'geolocation_lng': 'seller_lng',
    'geolocation_city': 'seller_geo_city',
    'geolocation_state': 'seller_geo_state'
})
# Add seller geolocation
df_sellers_enriched = df_sellers.merge(
    df_seller_geo,
    on='seller_zip_code_prefix',
    how='left',
    validate='m:1'
)
df_sellers_enriched.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,-22.893848,-47.061337,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,-22.383437,-46.947927,mogi-guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,-22.909572,-43.177703,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,04195,sao paulo,SP,-23.657242,-46.612831,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,-22.964803,-46.534419,braganca paulista,SP

In [144]:
# Create product-level features
df_products_features = df_products.copy()

df_products_features['product_volume_cm3'] = (
    df_products_features['product_length_cm'] *
    df_products_features['product_height_cm'] *
    df_products_features['product_width_cm']
)
# Add English product category names
df_products_features = df_products_features.merge(
    df_product_name_trans,
    on='product_category_name',
    how='left',
    validate='m:1'
)
# Fill missing category labels
df_products_features['product_category_name'] = (
    df_products_features['product_category_name'].fillna('unknown')
)
df_products_features['product_category_name_english'] = (
    df_products_features['product_category_name_english'].fillna('unknown')
)
df_products_features.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,2240.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,10800.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,2430.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,2704.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,4420.0,housewares

In [145]:
# Fill missing physical product values with median
df_products_features['product_weight_g'] = (
    df_products_features['product_weight_g']
    .fillna(df_products_features['product_weight_g'].median())
)
df_products_features['product_volume_cm3'] = (
    df_products_features['product_volume_cm3']
    .fillna(df_products_features['product_volume_cm3'].median())
)
df_products_features[
    ['product_category_name', 'product_category_name_english', 'product_weight_g', 'product_volume_cm3']
].isna().sum()

product_category_name            0
product_category_name_english    0
product_weight_g                 0
product_volume_cm3               0
dtype: int64

In [146]:
# Select product columns needed for order-level aggregation
product_cols = [
    'product_id',
    'product_category_name',
    'product_category_name_english',
    'product_weight_g',
    'product_volume_cm3'
]
# Add product information to order items
df_order_items_enriched = df_order_items.merge(
    df_products_features[product_cols],
    on='product_id',
    how='left',
    validate='m:1'
)
df_order_items_enriched.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_category_name_english,product_weight_g,product_volume_cm3
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19/09/2017 9:45,58.90,13.29,cool_stuff,cool_stuff,650.0,3528.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03/05/2017 11:05,239.90,19.93,pet_shop,pet_shop,30000.0,60000.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18/01/2018 14:48,199.00,17.87,moveis_decoracao,furniture_decor,3050.0,14157.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15/08/2018 10:10,12.99,12.79,perfumaria,perfumery,200.0,2400.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13/02/2017 13:57,199.90,18.14,ferramentas_jardim,garden_tools,3750.0,42000.0

In [147]:
# Select seller columns needed for order-level aggregation
seller_cols = [
    'seller_id',
    'seller_zip_code_prefix',
    'seller_city',
    'seller_state',
    'seller_lat',
    'seller_lng',
    'seller_geo_city',
    'seller_geo_state'
]
# Add seller information to order items
df_order_items_enriched = df_order_items_enriched.merge(
    df_sellers_enriched[seller_cols],
    on='seller_id',
    how='left',
    validate='m:1'
)
df_order_items_enriched.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_category_name_english,product_weight_g,product_volume_cm3,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19/09/2017 9:45,58.90,13.29,cool_stuff,cool_stuff,650.0,3528.0,27277,volta redonda,SP,-22.496953,-44.127492,volta redonda,RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03/05/2017 11:05,239.90,19.93,pet_shop,pet_shop,30000.0,60000.0,03471,sao paulo,SP,-23.565096,-46.518565,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18/01/2018 14:48,199.00,17.87,moveis_decoracao,furniture_decor,3050.0,14157.0,37564,borda da mata,MG,-22.262584,-46.171124,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15/08/2018 10:10,12.99,12.79,perfumaria,perfumery,200.0,2400.0,14403,franca,SP,-20.553624,-47.387359,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13/02/2017 13:57,199.90,18.14,ferramentas_jardim,garden_tools,3750.0,42000.0,87900,loanda,PR,-22.929384,-53.135873,loanda,PR

In [148]:
# Build order-level features from enriched item-level data
df_order_features = df_order_items_enriched.groupby('order_id').agg(
    item_count=('order_item_id', 'count'),
    product_count=('product_id', 'nunique'),
    category_count=('product_category_name_english', 'nunique'),
    seller_count=('seller_id', 'nunique'),
    
    total_price=('price', 'sum'),
    total_freight=('freight_value', 'sum'),
    total_weight_g=('product_weight_g', 'sum'),
    total_volume_cm3=('product_volume_cm3', 'sum'),
    
    product_id=('product_id', 'first'),
    product_category_name_english=('product_category_name_english', 'first'),
    
    seller_id=('seller_id', 'first'),
    seller_zip_code_prefix=('seller_zip_code_prefix', 'first'),
    seller_city=('seller_city', 'first'),
    seller_state=('seller_state', 'first'),
    seller_lat=('seller_lat', 'first'),
    seller_lng=('seller_lng', 'first'),
    seller_geo_city=('seller_geo_city', 'first'),
    seller_geo_state=('seller_geo_state', 'first')
).reset_index()

df_order_features.head(5)

,order_id,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,product_id,product_category_name_english,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,1,58.90,13.29,650.0,3528.0,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,48436dade18ac8b2bce089ec2a041202,27277,volta redonda,SP,-22.496953,-44.127492,volta redonda,RJ
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,1,239.90,19.93,30000.0,60000.0,e5f2d52b802189ee658865ca93d83a8f,pet_shop,dd7ddc04e1b6c2c614352b383efe2d36,03471,sao paulo,SP,-23.565096,-46.518565,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,1,1,1,199.00,17.87,3050.0,14157.0,c777355d18b72b67abbeef9df44fd0fd,furniture_decor,5b51032eddd242adc84c38acab88f23d,37564,borda da mata,MG,-22.262584,-46.171124,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,1,12.99,12.79,200.0,2400.0,7634da152a4610f1595efa32f14722fc,perfumery,9d7a1d34a5052409006425275ba1c2b4,14403,franca,SP,-20.553624,-47.387359,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,1,199.90,18.14,3750.0,42000.0,ac6c3623068f30de03045865e4e10089,garden_tools,df560393f3a51e74553ab94004ba5c87,87900,loanda,PR,-22.929384,-53.135873,loanda,PR

In [149]:
# Create order structure flags
df_order_features['multi_seller_flag'] = (
    df_order_features['seller_count'] > 1
).astype(int)

df_order_features['multi_product_flag'] = (
    df_order_features['product_count'] > 1
).astype(int)

df_order_features['freight_to_price_ratio'] = np.where(
    df_order_features['total_price'] > 0,
    df_order_features['total_freight'] / df_order_features['total_price'],
    0
)

In [150]:
# Classify order structure type
df_order_features['order_structure_type'] = np.where(
    (df_order_features['product_count'] == 1) &
    (df_order_features['seller_count'] == 1),
    'Homogeneous',
    'Complex'
)

df_order_features.head(5)

,order_id,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,product_id,product_category_name_english,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,1,58.90,13.29,650.0,3528.0,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,48436dade18ac8b2bce089ec2a041202,27277,volta redonda,SP,-22.496953,-44.127492,volta redonda,RJ,0,0,0.225637,Homogeneous
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,1,239.90,19.93,30000.0,60000.0,e5f2d52b802189ee658865ca93d83a8f,pet_shop,dd7ddc04e1b6c2c614352b383efe2d36,03471,sao paulo,SP,-23.565096,-46.518565,sao paulo,SP,0,0,0.083076,Homogeneous
2,000229ec398224ef6ca0657da4fc703e,1,1,1,1,199.00,17.87,3050.0,14157.0,c777355d18b72b67abbeef9df44fd0fd,furniture_decor,5b51032eddd242adc84c38acab88f23d,37564,borda da mata,MG,-22.262584,-46.171124,borda da mata,MG,0,0,0.089799,Homogeneous
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,1,12.99,12.79,200.0,2400.0,7634da152a4610f1595efa32f14722fc,perfumery,9d7a1d34a5052409006425275ba1c2b4,14403,franca,SP,-20.553624,-47.387359,franca,SP,0,0,0.984604,Homogeneous
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,1,199.90,18.14,3750.0,42000.0,ac6c3623068f30de03045865e4e10089,garden_tools,df560393f3a51e74553ab94004ba5c87,87900,loanda,PR,-22.929384,-53.135873,loanda,PR,0,0,0.090745,Homogeneous

In [151]:
# Keep product and seller details only for homogeneous orders
complex_order_mask = df_order_features['order_structure_type'] == 'Complex'

single_entity_cols = [
    'product_id',
    'product_category_name_english',
    'seller_id',
    'seller_zip_code_prefix',
    'seller_city',
    'seller_state',
    'seller_lat',
    'seller_lng',
    'seller_geo_city',
    'seller_geo_state'
]

df_order_features.loc[complex_order_mask, single_entity_cols] = np.nan

df_order_features.head(5)

,order_id,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,product_id,product_category_name_english,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,1,58.90,13.29,650.0,3528.0,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,48436dade18ac8b2bce089ec2a041202,27277,volta redonda,SP,-22.496953,-44.127492,volta redonda,RJ,0,0,0.225637,Homogeneous
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,1,239.90,19.93,30000.0,60000.0,e5f2d52b802189ee658865ca93d83a8f,pet_shop,dd7ddc04e1b6c2c614352b383efe2d36,03471,sao paulo,SP,-23.565096,-46.518565,sao paulo,SP,0,0,0.083076,Homogeneous
2,000229ec398224ef6ca0657da4fc703e,1,1,1,1,199.00,17.87,3050.0,14157.0,c777355d18b72b67abbeef9df44fd0fd,furniture_decor,5b51032eddd242adc84c38acab88f23d,37564,borda da mata,MG,-22.262584,-46.171124,borda da mata,MG,0,0,0.089799,Homogeneous
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,1,12.99,12.79,200.0,2400.0,7634da152a4610f1595efa32f14722fc,perfumery,9d7a1d34a5052409006425275ba1c2b4,14403,franca,SP,-20.553624,-47.387359,franca,SP,0,0,0.984604,Homogeneous
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,1,199.90,18.14,3750.0,42000.0,ac6c3623068f30de03045865e4e10089,garden_tools,df560393f3a51e74553ab94004ba5c87,87900,loanda,PR,-22.929384,-53.135873,loanda,PR,0,0,0.090745,Homogeneous

In [152]:
# Check whether each order appears only once
print("Is order_id unique:", df_order_features['order_id'].is_unique)
print("Order-level feature rows:", len(df_order_features))

Is order_id unique: True
Order-level feature rows: 98666

In [153]:
# Select review columns needed for the final master table
review_cols = [
    'order_id',
    'review_score'
]

# Select customer columns needed for the final master table
customer_cols = [
    'customer_id',
    'customer_unique_id',
    'customer_zip_code_prefix',
    'customer_city',
    'customer_state',
    'customer_lat',
    'customer_lng',
    'customer_geo_city',
    'customer_geo_state'
]

In [154]:
# Build final master order-level table
df_master_orders_final = df_orders_featured.merge(
    df_order_features,
    on='order_id',
    how='left',
    validate='1:1'
)

df_master_orders_final = df_master_orders_final.merge(
    df_reviews_order_level[review_cols],
    on='order_id',
    how='inner',
    validate='1:1'
)

df_master_orders_final = df_master_orders_final.merge(
    df_customers_enriched[customer_cols],
    on='customer_id',
    how='left',
    validate='m:1'
)

df_master_orders_final.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,product_id,product_category_name_english,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type,review_score,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_lat,customer_lng,customer_geo_city,customer_geo_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,11.0,2.366667,6.062500,8.436806,-7.107639,1,1,1,1,29.99,8.72,500.0,1976.0,87285b34884572647811a353c7ac498a,housewares,3504c0cb71d7fa48d967e0e4c94d59d9,09350,maua,SP,-23.680729,-46.444238,maua,SP,0,0,0.290764,Homogeneous,4.0,7c396fd4830fd04220f754e42b4e5bff,03149,sao paulo,SP,-23.576983,-46.587161,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,1843.0,0.463194,12.038889,13.781944,-5.356250,1,1,1,1,118.70,22.76,400.0,4693.0,595fac2a385ac33a80bd5114aec74eb8,perfumery,289cdb325fb7e7f891c38608bf9e0962,31570,belo horizonte,SP,-19.807681,-43.980427,belo horizonte,MG,0,0,0.191744,Homogeneous,4.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,-12.177924,-44.660711,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,17.0,0.204861,9.177778,9.394444,-17.245833,1,1,1,1,159.90,19.22,420.0,9576.0,aa4383b373c6aca5d8797843e5594415,auto,4869f7a5dfa277a7dca6462dcf3b52b2,14840,guariba,SP,-21.363502,-48.229601,guariba,SP,0,0,0.120200,Homogeneous,5.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,-16.745150,-48.514783,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,17.0,3.745833,9.450694,13.208333,-12.980556,1,1,1,1,45.00,27.20,450.0,6000.0,d0b61bfb1de832b15ba9d266ca96e5b0,pet_shop,66922902710d126a0e7d26b0e3805106,31842,belo horizonte,MG,-19.837682,-43.924053,belo horizonte,MG,0,0,0.604444,Homogeneous,5.0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,-5.774190,-35.271143,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,62.0,0.893056,1.938194,2.874306,-9.238194,1,1,1,1,19.90,8.72,250.0,11475.0,65266b2da20d04dbe00c5c2d3bb7859e,stationery,2c9e548be18521d1c43cde1c582c6de8,08752,mogi das cruzes,SP,-23.543395,-46.262086,mogi das cruzes,SP,0,0,0.438191,Homogeneous,5.0,72632f0f9dd73dfee390c9b22eb56dd6,09195,santo andre,SP,-23.676370,-46.514627,santo andre,SP

## 2. DATA PREPROCESSING & EDA

### 2.1. Dealing with Conversion

In [157]:
df_master_orders_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95815 entries, 0 to 95814
Data columns (total 44 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       95815 non-null  object
 1   customer_id                    95815 non-null  object
 2   order_status                   95815 non-null  object
 3   order_purchase_timestamp       95815 non-null  datetime64[ns]
 4   order_approved_at              95815 non-null  datetime64[ns]
 5   order_delivered_carrier_date   95815 non-null  datetime64[ns]
 6   order_delivered_customer_date  95815 non-null  datetime64[ns]
 7   order_estimated_delivery_date  95815 non-null  datetime64[ns]
 8   order_approval_time            95815 non-null  float64
 9   seller_handling_time           95815 non-null  float64
 10  carrier_transit_time           95815 non-null  float64
 11  total_delivery_lead_time       95815 non-null  float64
 12  promise_gap                    95815 non-null  float64
 13  item_count                     95815 non-null  int64
 14  product_count                  95815 non-null  int64
 15  category_count                 95815 non-null  int64
 16  seller_count                   95815 non-null  int64
 17  total_price                    95815 non-null  float64
 18  total_freight                  95815 non-null  float64
 19  total_weight_g                 95815 non-null  float64
 20  total_volume_cm3               95815 non-null  float64
 21  product_id                     92655 non-null  object
 22  product_category_name_english  92655 non-null  object
 23  seller_id                      92655 non-null  object
 24  seller_zip_code_prefix         92655 non-null  object
 25  seller_city                    92655 non-null  object
 26  seller_state                   92655 non-null  object
 27  seller_lat                     92446 non-null  float64
 28  seller_lng                     92446 non-null  float64
 29  seller_geo_city                92446 non-null  object
 30  seller_geo_state               92446 non-null  object
 31  multi_seller_flag              95815 non-null  int32
 32  multi_product_flag             95815 non-null  int32
 33  freight_to_price_ratio         95815 non-null  float64
 34  order_structure_type           95815 non-null  object
 35  review_score                   95815 non-null  float64
 36  customer_unique_id             95815 non-null  object
 37  customer_zip_code_prefix       95815 non-null  object
 38  customer_city                  95815 non-null  object
 39  customer_state                 95815 non-null  object
 40  customer_lat                   95552 non-null  float64
 41  customer_lng                   95552 non-null  float64
 42  customer_geo_city              95552 non-null  object
 43  customer_geo_state             95552 non-null  object
dtypes: datetime64[ns](5), float64(15), int32(2), int64(4), object(18)
memory usage: 31.4+ MB

### 3. Dealing with Missing Values

In [159]:
df_master_orders_final.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
order_approval_time                 0
seller_handling_time                0
carrier_transit_time                0
total_delivery_lead_time            0
promise_gap                         0
item_count                          0
product_count                       0
category_count                      0
seller_count                        0
total_price                         0
total_freight                       0
total_weight_g                      0
total_volume_cm3                    0
product_id                       3160
product_category_name_english    3160
seller_id                        3160
seller_zip_code_prefix           3160
seller_city                      3160
seller_state                     3160
seller_lat                       3369
seller_lng                       3369
seller_geo_city                  3369
seller_geo_state                 3369
multi_seller_flag                   0
multi_product_flag                  0
freight_to_price_ratio              0
order_structure_type                0
review_score                        0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
customer_lat                      263
customer_lng                      263
customer_geo_city                 263
customer_geo_state                263
dtype: int64

### 4. Dealing with Duplicate & Non-Unique Values

In [161]:
df_master_orders_final.duplicated().sum()

0

In [162]:
check_dup = {
    'order_id',
    'customer_id',
    'customer_unique_id',
    'product_id',
    'seller_id'
}
id_dup = {}
for i in check_dup:
    id_dup[i] = df_master_orders_final[i].is_unique 

id_dup

{'seller_id': False,
 'product_id': False,
 'customer_unique_id': False,
 'customer_id': True,
 'order_id': True}

### 5. Field Validity & Structural Checks

In [164]:
# Check whether key ID columns follow the expected 32-character hexadecimal format
id_columns = [
    'order_id',
    'customer_id',
    'customer_unique_id'
]

for col in id_columns:
    invalid_count = (
        ~df_master_orders_final[col]
        .astype(str)
        .str.match(r'^[a-f0-9]{32}$', na=False)
    ).sum()
    
    print(f"Invalid {col}: {invalid_count}")

Invalid order_id: 0
Invalid customer_id: 0
Invalid customer_unique_id: 0

In [165]:
# Check product_id and seller_id only when they are available
optional_id_columns = [
    'product_id',
    'seller_id'
]

for col in optional_id_columns:
    invalid_count = (
        df_master_orders_final[col].notna() &
        ~df_master_orders_final[col].astype(str).str.match(r'^[a-f0-9]{32}$', na=False)
    ).sum()
    
    print(f"Invalid {col}: {invalid_count}")

Invalid product_id: 0
Invalid seller_id: 0

In [166]:
# Check whether review_score is within the valid range from 1 to 5
invalid_review_score = df_master_orders_final[
    ~df_master_orders_final['review_score'].between(1, 5)
]

print("Invalid review_score rows:", len(invalid_review_score))

invalid_review_score.head(5)

Invalid review_score rows: 0

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_approval_time, seller_handling_time, carrier_transit_time, total_delivery_lead_time, promise_gap, item_count, product_count, category_count, seller_count, total_price, total_freight, total_weight_g, total_volume_cm3, product_id, product_category_name_english, seller_id, seller_zip_code_prefix, seller_city, seller_state, seller_lat, seller_lng, seller_geo_city, seller_geo_state, multi_seller_flag, multi_product_flag, freight_to_price_ratio, order_structure_type, review_score, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state, customer_lat, customer_lng, customer_geo_city, customer_geo_state]
Index: []

In [167]:
# Check whether numerical order-level features contain invalid negative values
numeric_cols = [
    'item_count',
    'product_count',
    'category_count',
    'seller_count',
    'total_price',
    'total_freight',
    'total_weight_g',
    'total_volume_cm3',
    'freight_to_price_ratio'
]

invalid_numeric_rows = df_master_orders_final[
    (df_master_orders_final[numeric_cols] < 0).any(axis=1)
]

print("Rows with negative numeric values:", len(invalid_numeric_rows))

invalid_numeric_rows.head(5)

Rows with negative numeric values: 0

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_approval_time, seller_handling_time, carrier_transit_time, total_delivery_lead_time, promise_gap, item_count, product_count, category_count, seller_count, total_price, total_freight, total_weight_g, total_volume_cm3, product_id, product_category_name_english, seller_id, seller_zip_code_prefix, seller_city, seller_state, seller_lat, seller_lng, seller_geo_city, seller_geo_state, multi_seller_flag, multi_product_flag, freight_to_price_ratio, order_structure_type, review_score, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state, customer_lat, customer_lng, customer_geo_city, customer_geo_state]
Index: []

In [168]:
# Check expected values in key categorical columns
valid_order_status = ['delivered']
valid_structure_types = ['Homogeneous', 'Complex']

invalid_status_rows = df_master_orders_final[
    ~df_master_orders_final['order_status'].isin(valid_order_status)
]

invalid_structure_type_rows = df_master_orders_final[
    ~df_master_orders_final['order_structure_type'].isin(valid_structure_types)
]

print("Invalid order_status rows:", len(invalid_status_rows))
print("Invalid order_structure_type rows:", len(invalid_structure_type_rows))

Invalid order_status rows: 6
Invalid order_structure_type rows: 0

In [169]:
df_master_orders_final = df_master_orders_final[
    df_master_orders_final['order_status'] == 'delivered'
]

In [170]:
# Identify timestamp inconsistencies
approval_after_carrier_mask = (
    df_master_orders_final['order_approved_at'] >
    df_master_orders_final['order_delivered_carrier_date']
)

carrier_after_customer_mask = (
    df_master_orders_final['order_delivered_carrier_date'] >
    df_master_orders_final['order_delivered_customer_date']
)

invalid_time_mask = approval_after_carrier_mask | carrier_after_customer_mask

In [171]:
# Summarize timestamp inconsistencies
time_issue_summary = pd.Series({
    'approval_after_carrier': approval_after_carrier_mask.sum(),
    'carrier_after_customer': carrier_after_customer_mask.sum(),
    'total_invalid_time_rows': invalid_time_mask.sum()
})

time_issue_summary

approval_after_carrier     1342
carrier_after_customer       23
total_invalid_time_rows    1365
dtype: int64

In [172]:
# Check the percentage of rows affected
invalid_time_percentage = invalid_time_mask.mean() * 100

print("Total rows before filtering:", len(df_master_orders_final))
print("Invalid time rows:", invalid_time_mask.sum())
print(f"Invalid time percentage: {invalid_time_percentage:.2f}%")

Total rows before filtering: 95809
Invalid time rows: 1365
Invalid time percentage: 1.42%

### Time Logic Validation and Filtering

The final master table is validated to ensure that delivery-related timestamps follow a meaningful chronological order for delivery performance analysis.

Two types of timestamp inconsistencies are identified:

- `approval_after_carrier`: cases where `order_approved_at` is later than `order_delivered_carrier_date`.
- `carrier_after_customer`: cases where `order_delivered_carrier_date` is later than `order_delivered_customer_date`.

The `carrier_after_customer` cases are treated as hard inconsistencies because the carrier handoff should occur before customer delivery.

The `approval_after_carrier` cases may reflect payment approval delays, system recording issues, or specific payment workflows. However, these rows produce negative `seller_handling_time`, which conflicts with the feature definition used in this project.

Therefore, both types of inconsistent rows are removed from the analytical dataset to keep delivery time features logically valid and interpretable.

In [174]:
# Remove rows with inconsistent delivery timestamp logic
df_master_orders_time_valid = df_master_orders_final[
    ~invalid_time_mask
].reset_index(drop=True)

In [175]:
# Recheck timestamp inconsistencies after filtering
approval_after_carrier_check = (
    df_master_orders_time_valid['order_approved_at'] >
    df_master_orders_time_valid['order_delivered_carrier_date']
).sum()

carrier_after_customer_check = (
    df_master_orders_time_valid['order_delivered_carrier_date'] >
    df_master_orders_time_valid['order_delivered_customer_date']
).sum()

print("Approval after carrier rows:", approval_after_carrier_check)
print("Carrier after customer rows:", carrier_after_customer_check)
print("Rows after filtering:", len(df_master_orders_time_valid))

Approval after carrier rows: 0
Carrier after customer rows: 0
Rows after filtering: 94444

In [181]:
# Check whether product and seller details are only missing for Complex orders
single_entity_cols = [
    'product_id',
    'product_category_name_english',
    'seller_id',
    'seller_zip_code_prefix',
    'seller_city',
    'seller_state'
]

homogeneous_missing_rows = df_master_orders_time_valid[
    (df_master_orders_time_valid['order_structure_type'] == 'Homogeneous') &
    (df_master_orders_time_valid[single_entity_cols].isna().any(axis=1))
]

print("Homogeneous orders with missing product/seller details:", len(homogeneous_missing_rows))

homogeneous_missing_rows[
    ['order_id', 'order_structure_type'] + single_entity_cols
].head(5)

Homogeneous orders with missing product/seller details: 0

Empty DataFrame
Columns: [order_id, order_structure_type, product_id, product_category_name_english, seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [183]:
df_master_orders_time_valid

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_approval_time,seller_handling_time,carrier_transit_time,total_delivery_lead_time,promise_gap,item_count,product_count,category_count,seller_count,total_price,total_freight,total_weight_g,total_volume_cm3,product_id,product_category_name_english,seller_id,seller_zip_code_prefix,seller_city,seller_state,seller_lat,seller_lng,seller_geo_city,seller_geo_state,multi_seller_flag,multi_product_flag,freight_to_price_ratio,order_structure_type,review_score,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,customer_lat,customer_lng,customer_geo_city,customer_geo_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,11.0,2.366667,6.062500,8.436806,-7.107639,1,1,1,1,29.99,8.72,500.0,1976.0,87285b34884572647811a353c7ac498a,housewares,3504c0cb71d7fa48d967e0e4c94d59d9,09350,maua,SP,-23.680729,-46.444238,maua,SP,0,0,0.290764,Homogeneous,4.0,7c396fd4830fd04220f754e42b4e5bff,03149,sao paulo,SP,-23.576983,-46.587161,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,1843.0,0.463194,12.038889,13.781944,-5.356250,1,1,1,1,118.70,22.76,400.0,4693.0,595fac2a385ac33a80bd5114aec74eb8,perfumery,289cdb325fb7e7f891c38608bf9e0962,31570,belo horizonte,SP,-19.807681,-43.980427,belo horizonte,MG,0,0,0.191744,Homogeneous,4.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,-12.177924,-44.660711,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,17.0,0.204861,9.177778,9.394444,-17.245833,1,1,1,1,159.90,19.22,420.0,9576.0,aa4383b373c6aca5d8797843e5594415,auto,4869f7a5dfa277a7dca6462dcf3b52b2,14840,guariba,SP,-21.363502,-48.229601,guariba,SP,0,0,0.120200,Homogeneous,5.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,-16.745150,-48.514783,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,17.0,3.745833,9.450694,13.208333,-12.980556,1,1,1,1,45.00,27.20,450.0,6000.0,d0b61bfb1de832b15ba9d266ca96e5b0,pet_shop,66922902710d126a0e7d26b0e3805106,31842,belo horizonte,MG,-19.837682,-43.924053,belo horizonte,MG,0,0,0.604444,Homogeneous,5.0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,-5.774190,-35.271143,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,62.0,0.893056,1.938194,2.874306,-9.238194,1,1,1,1,19.90,8.72,250.0,11475.0,65266b2da20d04dbe00c5c2d3bb7859e,stationery,2c9e548be18521d1c43cde1c582c6de8,08752,mogi das cruzes,SP,-23.543395,-46.262086,mogi das cruzes,SP,0,0,0.438191,Homogeneous,5.0,72632f0f9dd73dfee390c9b22eb56dd6,09195,santo andre,SP,-23.676370,-46.514627,santo andre,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94439,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:00,2017-03-09 09:54:00,2017-03-10 11:18:00,2017-03-17 15:08:00,2017-03-28,0.0,1.058333,7.159722,8.218056,-10.369444,1,1,1,1,72.00,13.08,1175.0,5148.0,ac35486adb7b02598c182c2ff2e05254,health_beauty,e24fc9fcd865784fb25705606fe3dfe7,12913,braganca paulista,SP,-22.961694,-46.523854,braganca paulista,SP,0,0,0.181667,Homogeneous,5.0,6359f309b166b0196dbf7ad2ac62bb5a,12209,sao jose dos campos,SP,-23.178000,-45.883818,sao jose dos campos,SP
94440,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,12.0,1.425000,20.760417,22.193750,-1.265972,1,1,1,1,174.90,20.10,4950.0,16000.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,baby,1f9ab4708f3056ede07124aad39a2554,17602,tupa,SP,-21.930548,-50.498348,tupa,SP,0,0,0.114923,Homogeneous,4.0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,-24.001500,-46.449864,praia grande,SP
94441,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,18.0,1.241667,23.605556,24.859722,-5.525000,1,1,1,1,205.99,65.02,13300.0,63360.0,b80910977a37536adeddd63663f916ad,home_appliances_2,d50d79cb34e38265a8649c383dcffd48,08290,sao paulo,SP,-23.553642,-46.452661,sao paulo,SP,0,0,0.315646,Homogeneous,5.0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,-17.898358,-39.373630,nova vicosa,BA
94442,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,8.0,3.749306,13.331250,17.086111,-20.019444,2,1,1,1,359.98,81.18,13100.0,16000.0,d1c427060a0f73f6b889a5c7c61f2ac4,computers_accessories,a1043bafd471dff536d0c462352beb48,37175,ilicinea,MG,-20.940578,-45.827237,ilicinea,MG,0,0,0.225513,Homogeneous,2.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,-22.562825,-42.694574,japuiba,RJ
94443,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,863.0,0.452083,6.622917,7.674306,-17.452778,1,1,1,1,68.50,18.36,150.0,1680.0,006619bbed68b000c8ba3f8725d5409e,health_beauty,ececbfcff9804a2d6b40f589df8eef2b,14407,franca,SP,-20.496251,-47.418434,franca,SP,0,0,0.268029,Homogeneous,5.0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,-25.764308,-49.720376,lapa,PR